# Generated by Django 3.1.4 on 2021-02-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('bot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_user', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('ready_to_use', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=4000)),
                ('description', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='UserTg',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BotView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertg')),
            ],
        ),
        migrations.CreateModel(
            name='BotLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_datetime', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertg')),
            ],
        ),
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertg')),
            ],
        ),
    ]
