# Generated by Django 3.1.4 on 2021-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='deleted',
            new_name='is_ban',
        ),
        migrations.RenameField(
            model_name='botlike',
            old_name='deal',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='botview',
            old_name='deal',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='usertg',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='bot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
