# Generated by Django 3.1.4 on 2021-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210207_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
