# Generated by Django 3.1.4 on 2021-02-07 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210207_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
