# Generated by Django 3.1.4 on 2021-02-07 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210207_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botcomment',
            old_name='deal',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='botcomment',
            old_name='like_datetime',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='botrating',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
